# -*- coding: UTF-8 -*-
DATA_TYPES = [
   ("statistics", u"統計文本資料"),
   ("books", u"文獻書籍"),
   ("pics_non_spatial", u"掃描圖像 (非空間類)"),
   ("pics_spatial", u"掃描圖像 (空間類)"),
   ("grid", u"網格資料"),
   ("vector", u"向量資料"),
   ("tin", u"不規則三角網"),
   ("steropair", u"立體像對"),
   ("multimedia", u"影音多媒體"),
]
#Coded by ISO 639-3
LANGUAGES = [
   ("zho", u"現代標準漢語 (zho)"),
   ("hak", u"客家語 (hak)"),
   ("nan", u"閩南語 (nan)"),
   ("yue", u"粵語 (yue)"),
   ("lzh", u"文言文 (lzh)"),
   ("jpn", u"日語 (jpn)"),
   ("eng", u"英語 (eng)"),
   ("spa", u"西班牙語 (spa)"),
   ("nld", u"荷蘭語 (nld)"),
   ("fos", u"西拉雅語 (fos)"),
   ("por", u"葡萄牙語 (por)"),
]
#Coded by RFC2978 (IANA Charset Registration Procedures)
ENCODINGS = [
   ("big5", u"big5"),
   ("utf-8", "UTF-8"),
   ("latin1", "ISO-8859-1/Latin-1"),
   ("gb2312", "GB2312"),
   ("gb18030", "GB18030"),
   ("shift_jis", "Shift_JIS"),
   ("euc-jp", "EUC-JP"),
]
#from themename.xlsx by Angela
THEME_KEYWORDS = [
   ("", u"未選取"),
   ("alluvium", u"(地形) 沖積層"),
   ("coastal", u"(地形) 海岸"),
   ("coastal drifting", u"(地形) 海岸變遷"),
   ("coastal erosion", u"(地形) 海岸侵蝕"),
   ("Earthquake ", u"(地形) 地震"),
   ("erosion", u"(地形) 侵蝕[作用]"),
   ("Fault ", u"(地形) 斷層"),
   ("flood plain", u"(地形) 氾濫平原"),
   ("flood plain swamp", u"(地形) 氾濫[平]原沼澤"),
   ("floodplain", u"(地形) 氾濫[平]原"),
   ("Geology ", u"(地形) 地質"),
   ("geomorphic change", u"(地形) 地形變遷"),
   ("hill", u"(地形) 丘陵"),
   ("hydraulic erosion", u"(地形) 沖蝕"),
   ("Lagoon ", u"(地形) 潟湖"),
   ("land subsidence", u"(地形) 地層下陷"),
   ("landform /topography", u"(地形) 地形"),
   ("littoral drift", u"(地形) 沿岸漂沙"),
   ("longshore bar", u"(地形) 沿岸沙洲"),
   ("longshore current", u"(地形) 沿岸流"),
   ("longshore drift", u"(地形) 沿岸漂沙"),
   ("claimed tidal flat", u"(水文) 海埔地"),
   ("flood peak", u"(水文) 洪峰"),
   ("paleochannel", u"(水文) 古河道"),
   ("peak discharge", u"(水文) 洪峰流量"),
   ("precipitation", u"(水文) 降水"),
   ("precipitation intensity", u"(水文) 降水強度"),
   ("precipitation variation", u"(水文) 降水量變率"),
   ("Rainfall ", u"(水文) 雨量"),
   ("rainfall intensity", u"(水文) 降雨強度"),
   ("surface runoff", u"(水文) 地表逕流"),
   ("Typhoon ", u"(水文) 颱風"),
   ("unconfined groundwater", u"(水文) 自由地下水"),
   ("water quality", u"(水文) 水質"),
   ("water resources", u"(水文) 水資源"),
   ("Well ", u"(水文) 水井"),
   ("Wetlands", u"(水文) 濕地"),
   ("alluvial soil", u"(土壤) 沖積土"),
   ("desertification", u"(土壤) 沙漠化"),
   ("Fluvisol", u"(土壤) 沖積土"),
   ("soil alkalization", u"(土壤) 土壤鹽鹼化"),
   ("Soil Erosion", u"(土壤) 土壤侵蝕"),
   ("soil liquefaction", u"(土壤) 土壤液化"),
   ("bio-indicator", u"(生物) 生物指標"),
   ("ecological balance", u"(生物) 生態平衡"),
   ("ecosystem", u"(生物) 生態系統"),
   ("natural landscape", u"(生物) 自然景觀"),
   ("natural landscape zone", u"(生物) 自然景觀帶"),
   ("natural resources", u"(生物) 自然資源"),
   ("Climate ", u"(氣候) 氣候"),
   ("climatic change", u"(氣候) 氣候變遷"),
   ("climatic revolution", u"(氣候) 氣候演變"),
   ("climatic variation", u"(氣候) 氣候變化"),
   ("Flood ", u"(氣候) 洪水"),
   ("flood damage", u"(氣候) 水災"),
   ("Meiyu", u"(氣候) 梅雨"),
   ("Mei-yu", u"(氣候) 梅雨"),
   ("monsoon", u"(氣候) 季風"),
   ("plum rain", u"(氣候) 梅雨"),
   ("birth rate", u"(人口) 出生率"),
   ("death rate", u"(人口) 死亡率"),
   ("Demographic composition ", u"(人口) 人口組成"),
   ("dependent population", u"(人口) 依賴人口"),
   ("Disease", u"(人口) 疾病"),
   ("fertility rates", u"(人口) 生育率"),
   ("floating population", u"(人口) 流動人口"),
   ("mortality rate", u"(人口) 死亡率"),
   ("natural growth rate", u"(人口) 自然成長率"),
   ("natural increase", u"(人口) 自然增加"),
   ("Population", u"(人口) 人口"),
   ("population distribution", u"(人口) 人口分布"),
   ("rate of natural increase", u"(人口) 自然增加率"),
   ("community", u"(聚落) 社區"),
   ("community construction", u"(聚落) 社區營造"),
   ("community development", u"(聚落) 社區發展"),
   ("rural-urban relations", u"(聚落) 城鄉關係"),
   ("Settlements ", u"(聚落) 聚落"),
   ("urban diffusion", u"(聚落) 都市擴張"),
   ("urban expansion", u"(聚落) 都市擴張"),
   ("urban form", u"(聚落) 都市形態"),
   ("urban function", u"(聚落) 都市機能"),
   ("urban growth", u"(聚落) 都市成長"),
   ("urban planning", u"(聚落) 都市計畫"),
   ("urban renewal", u"(聚落) 都市更新"),
   ("urban structure", u"(聚落) 都市結構"),
   ("urbanization", u"(聚落) 都市化"),
   ("Agriculture ", u"(經濟) 農業"),
   ("Aquaculture", u"(經濟) 養殖漁業"),
   ("Crop rotations", u"(經濟) 作物輪作"),
   ("ecological agriculture", u"(經濟) 生態農業"),
   ("economies of scales", u"(經濟) 規模經濟"),
   ("Fisheries ", u"(經濟) 漁業"),
   ("heavy industry", u"(經濟) 重工業"),
   ("Industry ", u"(經濟) 產業"),
   ("Inflation", u"(經濟) 通貨膨脹"),
   ("labor-intensive industry", u"(經濟) 勞力密集產業"),
   ("labour intensive", u"(經濟) 勞力密集"),
   ("Mining ", u"(經濟) 礦業"),
   ("organic agriculture", u"(經濟) 有機農業"),
   ("Salt ", u"(經濟) 鹽業"),
   ("technology intensive", u"(經濟) 技術密集"),
   ("accessibility", u"(交通) 易達性；可達性"),
   ("National Spatial Planning", u"(政治) 國土規劃"),
   ("territorial development", u"(政治) 國土發展"),
   ("NGIS{=National Geographic Information System}", u"(政治) 國土資訊系統"),
   ("territorial resources", u"(政治) 國土資源"),
   ("territorial management", u"(政治) 國土管理"),
   ("Administrative boundaries", u"(其他) 行政區界"),
   ("aerial photographs", u"(其他) 相片基本圖"),
   ("Aerial photos", u"(其他) 航照"),
   ("Average Slope", u"(其他) 平均坡度"),
   ("cadastral map", u"(其他) 地籍圖"),
   ("Digital Elevation Model", u"(其他) 數值高程"),
   ("Digital Orthophoto Map{= DOM}", u"(其他) 正射影像"),
   ("environmental carrying capacity", u"(其他) 環境負載力"),
   ("environmental changes", u"(其他) 環境變遷"),
   ("environmental monitoring", u"(其他) 環境監測"),
   ("geological map", u"(其他) 地質圖"),
   ("Historical Maps", u"(其他) 歷史地圖"),
   ("land suitability", u"(其他) 土地適宜性"),
   ("Land Use", u"(其他) 土地利用"),
   ("orthophotomap", u"(其他) 正射影像圖"),
   ("orthophotos", u"(其他) 正射影像"),
   ("Satellite Images ", u"(其他) 衛星影像"),
   ("soil map", u"(其他) 土壤圖"),
   ("spatial analysis", u"(其他) 空間分析"),
   ("spatial distribution", u"(其他) 空間分布"),
   ("Taiwan Baotu", u"(其他) 臺灣堡圖"),
   ("The basic topographic maps ", u"(其他) 基本地形圖"),
   ("Tomographic ", u"(其他) 斷層"),
   ("topographic map", u"(其他) 地形圖；等高線地形圖"),
]
#from placename.csv by Dongpo
LOC_KEYWORDS = [
   ("1", u"七股區"),
   ("2", u"下營區"),
   ("3", u"中西區"),
   ("4", u"仁德區"),
   ("5", u"佳里區"),
   ("6", u"六甲區"),
   ("7", u"北區"),
   ("8", u"北門區"),
   ("9", u"南化區"),
   ("10", u"南區"),
   ("11", u"台南市"),
   ("12", u"善化區"),
   ("13", u"大內區"),
   ("14", u"學甲區"),
   ("15", u"安南區"),
   ("16", u"安定區"),
   ("17", u"安平區"),
   ("18", u"官田區"),
   ("19", u"將軍區"),
   ("20", u"山上區"),
   ("21", u"左鎮區"),
   ("22", u"後壁區"),
   ("23", u"新化區"),
   ("24", u"新市區"),
   ("25", u"新營區"),
   ("26", u"東區"),
   ("27", u"東山區"),
   ("28", u"柳營區"),
   ("29", u"楠西區"),
   ("30", u"歸仁區"),
   ("31", u"永康區"),
   ("32", u"玉井區"),
   ("33", u"白河區"),
   ("34", u"西港區"),
   ("35", u"關廟區"),
   ("36", u"鹽水區"),
   ("37", u"麻豆區"),
   ("38", u"龍崎區"),
   ("39", u"新港社"),
   ("40", u"歐王社"),
   ("41", u"蕭壟社"),
   ("42", u"北線尾"),
   ("43", u"鹿耳門"),
   ("44", u"赤崁樓"),
   ("45", u"熱蘭遮城"),
   ("46", u"紅毛城"),
   ("47", u"大目降社"),
   ("48", u"赤崁街"),
   ("49", u"赤崁社"),
   ("50", u"大員"),
   ("51", u"台江"),
   ("52", u"赤崁"),
   ("53", u"麻豆社"),
   ("54", u"噍吧哖"),
   ("55", u"哆喀嘓社"),
   ("56", u"蕭壟溪"),
   ("57", u"新港溪"),
   ("58", u"清水溪"),
   ("59", u"鹽水溪"),
   ("60", u"堯港"),
   ("61", u"下淡水社"),
   ("62", u"打狗"),
   ("63", u"放索溪"),
   ("64", u"萬丹"),
   ("65", u"目加溜灣"),
   ("66", u"大武壟社"),
   ("67", u"芒仔芒社"),
   ("68", u"加老灣"),
   ("69", u"茄藤社"),
   ("70", u"漁夫角"),
   ("71", u"上淡水社"),
   ("72", u"瑯嶠"),
   ("73", u"搭樓社"),
   ("74", u"力力社"),
   ("75", u"加祿堂"),
   ("76", u"阿猴社"),
   ("77", u"大澤機社"),
   ("78", u"打狗山"),
   ("79", u"小琉球嶼"),
   ("80", u"淡水溪"),
   ("81", u"放索社"),
   ("82", u"魍港"),
   ("83", u"笨港"),
   ("84", u"打貓社"),
   ("85", u"他里霧社"),
   ("86", u"斗六社"),
   ("87", u"猴悶社"),
   ("88", u"魍港城堡"),
   ("89", u"漁夫島"),
   ("90", u"華武壟社"),
   ("91", u"大坵田"),
   ("92", u"龜佛山"),
   ("93", u"槺榔"),
   ("94", u"鹿仔草"),
   ("95", u"南勢竹"),
   ("96", u"龜仔港"),
   ("97", u"土獅仔"),
   ("98", u"諸羅山社"),
   ("99", u"笨港溪"),
   ("100", u"麻豆溪"),
   ("101", u"井水港"),
   ("102", u"北新"),
   ("103", u"二鯤鯓"),
   ("104", u"三鯤鯓"),
   ("105", u"四鯤鯓"),
   ("106", u"安平港"),
   ("107", u"安平街"),
   ("108", u"南鯤身廟"),
   ("109", u"大道公廟"),
   ("110", u"關帝廟"),
]
TEMP_RES = [
   ("year", u"年"),
   ("decade", u"十年"),
   ("century", u"一百年"),
   ("date", u"日"),
   ("month", u"月"),
]
